# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    # labels:
    #   - "dependencies"
    # assignees:
    #   - your-username
    # reviewers:
    #   - reviewer1
    #   - reviewer2
    # ignore:
    #   - dependency-1
    #   - dependency-2
    # allow:
    #   - dependency-3
    # package-aliases:
    #   "old-package-name": "new-package-name"
