declare module "@editorjs/embed";
declare module "@editorjs/table";
declare module "@editorjs/list";
declare module "@editorjs/code";
declare module "@editorjs/link";
declare module "@editorjs/inline-code";
declare module "@editorjs/image";
declare module "@editorjs/quote";
declare module "@editorjs/marker";
